title: "CSD: Children's Song Dataset for Singing Voice Research"
description: Music and Audio Computing Lab, KAIST

theme: jekyll-theme-cayman

official_url: https://soonbeomchoi.github.io/CSD-Blog/

github:
  repository_url: https://github.com/emotiontts/emotiontts_open_db/tree/master/CSD