title: "CSD: Children's Song Dataset for Singing Voice Research"
institution: Music and Audio Computing Lab, KAIST

theme: 

github:
  repository_url: https://github.com/emotiontts/emotiontts_open_db/tree/master/CSD